import { Button, Input, Loading, Spacer } from "@nextui-org/react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Crypto Wallet | SOLANA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="card">
        <h1>Crypto Wallet</h1>
        <img src="/wallet.webp" width="100%" />
        <p>
          <b>SOLANA non-custodial crypto wallet</b>
        </p>

        <Link href="/new-wallet">
          <Button color="success" shadow className="btn" size="lg">
            Create New Wallet
          </Button>
        </Link>

        <Link href="/import-wallet">
          <Button shadow className="btn" size="lg">
            Import Wallet
          </Button>
        </Link>
      </div>
    </div>
  );
}
